<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @copyright  Copyright (c) 2009-2010 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<div class="footer-container">
    <div class="footer">
        <?php echo $this->getChildHtml('bottomContainer') ?>
        <div class="f-right">
            <?php echo $this->getChildHtml('newsletter') ?>
            <?php echo $this->getChildHtml('store_switcher') ?>
        </div>
        <div class="f-left">
            <?php echo $this->getChildHtml('cms_footer_links') ?>
            <?php echo $this->getChildHtml('footer_links') ?>
            <address><?php echo $this->getCopyright(); ?></address><?php echo base64_decode('PGRpdiBjbGFzcz0iYXctc3RvcmUtbGluayI+PGEgaHJlZj0iaHR0cDovL2Vjb21tZXJjZS5haGVhZHdvcmtzLmNvbS9tYWdlbnRvLXRoZW1lcy1hbmQtdGVtcGxhdGVzLmh0bWwiPk1hZ2VudG8gVGhlbWUgYnkgYWhlYWRXb3JrczwvYT48L2Rpdj4='); ?>
        </div>
    </div>
</div>
