<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @copyright  Copyright (c) 2009-2010 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<div class="header-container">
    <div class="quick-access">
        <?php echo $this->getChildHtml('store_language') ?>
        <div class="quick-access-green">
			  <p class="welcome-msg"><?php echo $this->getWelcome()?></p>
			  <?php echo $this->getChildHtml('topLinks') ?>
		  </div>
		  <div class="clear"></div>
    </div>
	 <div class="header">
        <?php if ($this->getIsHomePage()):?>
        <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
        <?php else:?>
        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
        <?php endif?>
        <?php echo $this->getChildHtml('topMenu') ?>
        <div class="top-bar">
            <?php echo $this->getChildHtml('topSearch') ?>
        </div>
    </div>
    <?php if($this->getChildHtml('breadcrumbs')) : ?>
    <div class="top-container">
        <?php echo $this->getChildHtml('breadcrumbs'); ?>
    </div>
    <?php endif; ?>
</div>
