<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Advancedmenu
 * @copyright  Copyright (c) 2009-2010 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php $_isFirst = true; ?>
<div class="aw-am-block aw-am-vsb">
<div class="aw-vpln-mnu aw-am-body"<?php if($this->getStyleId()): ?> id="<?php echo $this->getStyleId(); ?>"<?php endif; ?>>
<?php foreach( $this->getCategoriesData() as $i ): ?>	
	<?php if ( $i['level'] == 0 ): ?>
		<?php if (!$_isFirst): ?>
		</ul>
		<?php endif; ?>
		<ul>
	<li class="level<?php echo $i['level'];?> aw-am-level<?php echo $i['level'];?>  nav-<?php if ($i['hasChildren']): echo " parent"; endif;?><?php if ( $i['active'] && ($i['level'] == 0) && $this->confMarkCurrent() ): echo " active"; endif; ?>" style="cursor:pointer;">
		<a href="<?php echo $i['Url'];?>"><span><?php echo $i['name'];?></span></a>
	</li>			
	<?php else: ?>			
	<li class="level<?php echo $i['level'];?> aw-am-level<?php echo $i['level'];?>  nav-<?php if ($i['hasChildren']): echo " parent"; endif;?><?php if ( $i['current'] && $this->confMarkCurrent() ): echo " current"; endif;?>" style="cursor:pointer;">
		<a href="<?php echo $i['Url'];?>"><span><?php echo $i['name'];?></span></a>
	</li>
	<?php endif; ?>					
	<?php $_isFirst = false; ?>
<?php endforeach; ?>
<?php if ( count( $this->getCategoriesData() ) ): ?>
	</ul>	
<?php endif; ?>
</div></div>

